# Generated by Django 3.0.3 on 2020-03-01 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Thoughts', '0002_thought_connected_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thought',
            new_name='Post',
        ),
    ]
