# Generated by Django 3.0.3 on 2020-03-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoughts', '0004_auto_20200301_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
