# Generated by Django 3.0.3 on 2020-03-13 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Thoughts', '0006_auto_20200301_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentUser', to=settings.AUTH_USER_MODEL)),
                ('connected_to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentPost', to='Thoughts.Post')),
            ],
        ),
    ]
