# Generated by Django 3.0.3 on 2020-04-04 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thoughts', '0009_auto_20200314_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostComments', to='Thoughts.Comment'),
        ),
    ]
