# Generated by Django 3.0.3 on 2020-04-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoughts', '0013_auto_20200404_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='Thoughts.Comment'),
        ),
    ]
