# Generated by Django 3.0.3 on 2020-03-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExtendsUserModel', '0002_auto_20200227_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
