# Generated by Django 3.0.3 on 2020-03-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtendsUserModel', '0004_auto_20200301_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(height_field=325, null=True, upload_to='', width_field=325),
        ),
    ]
