# Generated by Django 3.0.3 on 2020-03-17 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtendsUserModel', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
