# Generated by Django 3.0.3 on 2020-03-17 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtendsUserModel', '0006_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(related_name='user_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
