# Generated by Django 3.0.3 on 2020-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtendsUserModel', '0008_auto_20200317_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field=325, null=True, upload_to='', width_field=325),
        ),
    ]
