# Generated by Django 3.0.3 on 2020-03-19 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtendsUserModel', '0009_auto_20200319_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_requests_from',
            field=models.ManyToManyField(blank=True, related_name='user_friend_requests_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend_requests_to',
            field=models.ManyToManyField(blank=True, related_name='user_friend_requests_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
