# Generated by Django 3.0.3 on 2020-03-19 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_connected_to', to=settings.AUTH_USER_MODEL)),
                ('dialog_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_with', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(to='Communication.Message')),
            ],
        ),
    ]
