# Generated by Django 3.0.3 on 2020-03-22 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Communication', '0002_dialog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='dialog_with',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='connected_to',
        ),
        migrations.AddField(
            model_name='dialog',
            name='connected_to',
            field=models.ManyToManyField(related_name='dialog_connected_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
