# Generated by Django 3.0.3 on 2020-03-22 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Communication', '0003_auto_20200322_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='dialog_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dial_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='connected_to',
        ),
        migrations.AddField(
            model_name='dialog',
            name='connected_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
